name: vision_comp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - opencv
  - numpy
  - matplotlib
  - jupyter
  - notebook
  - scikit-image
  - seaborn
  - ipywidgets
  - pip
  - pip:
    - opencv-python
